version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
       - "27018:27017"
    volumes:
      - mongo-data:/data/db

  python-app:
    build: .
    container_name: my-python-app
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - "8501:8501"

volumes:
  mongo-data: