version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
       - "27018:27017"
    volumes:
      - mongo-data:/data/db

  python-app:
    image: balrog000/my-python-app:latest
    build: .
    container_name: my-python-app
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G


volumes:
  mongo-data: